# wrangler.toml
name = 'llapi'
main = "src/index.py"
compatibility_date = "2024-01-01"

[env.production]
name = "llapi"

[[d1_databases]]
binding = "qdb"
database_name = "qdb"
database_id = "b99b874c-a976-4768-b96c-7c9c676c4ce5"

[vars]
SITE_URL = "https://your-site.com"
SITE_NAME = "AI API Proxy"

# Python相关配置
[build]
command = ""

# 确保包含所有必要的文件
[site]
bucket = "./dist"